name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d # v1.8.0
        with:
          version: nightly

      - name: Forge lint
        run: |
          forge lint
        id: lint

      - name: Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      # - name: Forge tests
      #   run: |
      #     forge test -vvv --rpc-url ${{ secrets.BSC_RPC_URL }}
      #   id: test
